# Generated by Django 4.0.6 on 2022-07-29 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tiempo_reserva',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario_reserva',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
