# Generated by Django 4.0.6 on 2022-07-29 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_reserva_descripcion_reserva_tiempo_reserva_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='tiempo_reserva',
            new_name='tiempo_fin',
        ),
        migrations.AddField(
            model_name='reserva',
            name='tiempo_inicio',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
