# Generated by Django 4.0.6 on 2022-07-30 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_rename_tiempo_reserva_reserva_tiempo_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tiempo_fin',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tiempo_inicio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
