# Generated by Django 4.0.6 on 2022-07-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_alter_reserva_tiempo_fin_alter_reserva_tiempo_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_reserva',
        ),
    ]
