# Generated by Django 4.0.6 on 2022-07-30 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_remove_reserva_fecha_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tiempo_fin',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
