# Generated by Django 4.0.6 on 2022-07-31 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0002_remove_sala_sala_id_sala_reserva_id'),
        ('reserva', '0006_alter_reserva_tiempo_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='sala_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sala.sala'),
        ),
    ]
