# Generated by Django 4.0.6 on 2022-08-20 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reserva', '0007_reserva_sala_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='usuario_reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
