# Generated by Django 4.0.6 on 2022-08-23 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0005_remove_sala_estado'),
        ('reserva', '0008_remove_reserva_usuario_reserva_reserva_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='invitados',
            field=models.EmailField(blank=True, default=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='titulo',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sala_id',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='sala.sala'),
        ),
    ]
