# Generated by Django 4.1 on 2022-08-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0005_remove_sala_estado'),
        ('reserva', '0008_remove_reserva_usuario_reserva_reserva_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='sala_id',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='sala.sala'),
        ),
    ]
