# Generated by Django 4.0.6 on 2022-08-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_reserva_invitados_reserva_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='invitados',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
