# Generated by Django 4.1 on 2022-08-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_alter_reserva_sala_id'),
        ('reserva', '0010_alter_reserva_invitados'),
    ]

    operations = [
    ]
