# Generated by Django 4.0.6 on 2022-08-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0010_alter_reserva_invitados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
