# Generated by Django 4.1 on 2022-08-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0011_alter_reserva_descripcion'),
        ('reserva', '0011_merge_20220824_1624'),
    ]

    operations = [
    ]
