# Generated by Django 4.0.6 on 2022-08-30 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0007_alter_sala_color'),
        ('reserva', '0012_merge_20220829_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='sala_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='sala.sala'),
        ),
    ]
