# Generated by Django 4.1 on 2023-04-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0015_reserva_recordatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='invitados',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
