# Generated by Django 4.1.5 on 2023-04-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserva", "0016_alter_reserva_invitados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="invitados",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
