# Generated by Django 4.1 on 2022-09-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=50)),
                ('host_user', models.CharField(max_length=50)),
                ('host_password', models.CharField(max_length=50)),
                ('host_port', models.CharField(max_length=50)),
            ],
        ),
    ]
