# Generated by Django 4.1 on 2022-09-05 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuracion',
            new_name='ConfigEmail',
        ),
    ]
