# Generated by Django 4.0.4 on 2026-04-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_rename_configuracion_configemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='configemail',
            name='default_from_email',
            field=models.EmailField(default='web@vic.uy', max_length=254),
        ),
        migrations.AddField(
            model_name='configemail',
            name='use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configemail',
            name='use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configemail',
            name='email_host',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='configemail',
            name='host_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='configemail',
            name='host_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AlterField(
            model_name='configemail',
            name='host_user',
            field=models.CharField(max_length=100),
        ),
    ]
