# Generated by Django 4.0.6 on 2022-07-24 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(null=True)),
                ('sala_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala.sala')),
            ],
        ),
    ]
