# Generated by Django 4.0.6 on 2022-08-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0002_remove_sala_sala_id_sala_reserva_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='reserva_id',
        ),
    ]
