# Generated by Django 4.0.6 on 2022-08-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0004_alter_sala_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='estado',
        ),
    ]
