# Generated by Django 4.1 on 2022-08-29 18:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0006_sala_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
